//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wordle_analogue.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wordle_analogue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alphabet_resized {
            get {
                object obj = ResourceManager.GetObject("alphabet_resized", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на абажур
        ///аббат
        ///абзац
        ///аборт
        ///абрек
        ///абрис
        ///абсурд
        ///абхазы
        ///аванс
        ///авария
        ///аварцы
        ///авгиев
        ///август
        ///авизо
        ///авось
        ///аврал
        ///автол
        ///автор
        ///атава
        ///агент
        ///агитка
        ///агнец
        ///агония
        ///адажио
        ///адамов
        ///адепт
        ///адрес
        ///адский
        ///адыги
        ///азалия
        ///азарт
        ///азбука
        ///азиаты
        ///азимут
        ///аймак
        ///акать
        ///акация
        ///аккорд
        ///акриды
        ///актёр
        ///актив
        ///актив
        ///акула
        ///акушер
        ///акцент
        ///акция
        ///акция
        ///алеть
        ///алеуты
        ///алиби
        ///алкать
        ///алкаш
        ///аллах
        ///аллея
        ///аллюр
        ///алмаз
        ///алтарь
        ///алтын
        ///алчный
        ///алыча
        ///альбом
        ///альков
        ///альма
        ///альфа
        ///альфа
        ///альянс
        ///амбал
        ///амбар
        ///амвон
        ///а [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string dictionary_5_6_utf_8 {
            get {
                return ResourceManager.GetString("dictionary_5-6_utf-8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на а
        ///а
        ///а
        ///а
        ///абажур
        ///абазинский
        ///абазины
        ///аббат
        ///аббатиса
        ///аббатство
        ///аббревиатура
        ///аберрация
        ///абзац
        ///абиссинский
        ///абиссинцы
        ///абитуриент
        ///абонемент
        ///абонент
        ///абонировать
        ///абордаж
        ///абориген
        ///аборигенный
        ///аборт
        ///абортивный
        ///абразив
        ///абракадабра
        ///абрек
        ///абрикос
        ///абрикосовый
        ///абрис
        ///абсентеизм
        ///абсолют
        ///абсолютизм
        ///абсолютный
        ///абстрагировать
        ///абстрагироваться
        ///абстрактный
        ///абстракционизм
        ///абстракционист
        ///абстракция
        ///абсурд
        ///абсурдный
        ///абсцесс
        ///абхазский
        ///абхазско
        ///абхазы
        ///абы
        ///авангард
        ///авангардизм
        ///авангардист
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string dictionary_utf_8 {
            get {
                return ResourceManager.GetString("dictionary_utf-8", resourceCulture);
            }
        }
    }
}
